title: My Jekyll Site
description: A blog hosted on GitHub Pages
baseurl: "/my-jekyll-site" # Leave empty if deploying to username.github.io
url: "https://username.github.io" # Base URL of your site
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# emiliocastorena.github.io
# Project title
## Adv GIS
